var nomevelha = prompt('Qual o nome da pessoa mais velha?')
var idadevelha = prompt('Qual a idade da pessoa mais velha?')  
var nomenovo = prompt('Qual o nome da pessoa mais nova?')
var idadenovo = prompt('Qual a idade da pessoa mais nova?')
alert('O nome da pessoa mais velha é: ' + nomevelha + ' e sua idade é: ' + idadevelha)
alert('O nome da pessoa mais nova é: ' + nomenovo + ' e sua idade é: ' + idadenovo)
alert('A diferença de idade entre ' + nomevelha + ' e '+ nomenovo + ' é: ' + (idadevelha - idadenovo))