alert('Bem vindo, a seguir pediremos que informe alguns dados')
var nome = prompt('Digite seu nome:')
var idade = prompt('Digite sua idade:')
prompt('confime sua idade:')
alert('O nome digitado foi: ' + nome + ' e sua idade foi: ' + idade)